# Generated by Django 5.2.3 on 2025-06-27 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='api_comment_article_0a8f73_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'created_at'], name='api_comment_article_121554_idx'),
        ),
    ]
