# Generated by Django 5.2.3 on 2025-06-27 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_comment_api_comment_article_0a8f73_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='moderated_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='moderated_by',
        ),
    ]
