# Generated by Django 5.2.3 on 2025-07-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_readinghistory_read_duration_like_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Text field identifier', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Text content')),
                ('description', models.CharField(blank=True, help_text='Description of this text field', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Text Configuration',
                'verbose_name_plural': 'Text Configurations',
                'ordering': ['key'],
            },
        ),
    ]
