# Generated by Django 5.2.3 on 2025-07-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_textconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Contact person's name", max_length=100)),
                ('email', models.EmailField(help_text="Contact person's email", max_length=254)),
                ('phone', models.CharField(blank=True, help_text="Contact person's phone number", max_length=20, null=True)),
                ('request_service', models.CharField(choices=[('Consulting', 'Consulting'), ('Development', 'Development'), ('Marketing', 'Marketing'), ('Support', 'Support')], help_text='Requested service type', max_length=20)),
                ('request_content', models.TextField(help_text='Detailed request content/message')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template identifier', max_length=50, unique=True)),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                ('content', models.TextField(help_text='Email content with variable placeholders')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Available variables for template substitution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['name'],
            },
        ),
    ]
