# Generated by Django 5.2.3 on 2025-07-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contact_emailtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['template_type', 'name'], 'verbose_name': 'Email Template', 'verbose_name_plural': 'Email Templates'},
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(blank=True, help_text='Email body content (legacy field, use content instead)'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this template is active'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='template_type',
            field=models.CharField(choices=[('thank_you', 'Thank You'), ('welcome', 'Welcome'), ('notification', 'Notification'), ('reminder', 'Reminder')], default='thank_you', help_text='Type of email template', max_length=20),
        ),
    ]
