# Generated by Django 5.2.3 on 2025-06-30 09:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_increase_cloudinary_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='article_content_image'),
        ),
    ]
