# Generated by Django 5.2.3 on 2025-07-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_articleimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinghistory',
            name='read_duration',
        ),
    ]
