# Generated by Django 5.2.3 on 2025-07-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_readinghistory_read_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinghistory',
            name='read_duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
