# Generated by Django 5.2.3 on 2025-07-01 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_readinghistory_read_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinghistory',
            name='read_duration',
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
